### ISSUE TITLE
Login / Logout messages are not working

### ISSUE THREAD

**Issue by RedGl0w** [TI-Planet/ShoutBot#79]
**Describe the bug**
Since 24/03/2022 (around 11am CEST), the login logouts messages (such as the one just after) aren't anymore sent.
It is very likely to be related to the changes made by @adriweb on the tibot a few minutes after the last login message

**Screenshots**
![image](https://user-images.githubusercontent.com/43498612/229596051-ab0592a5-4f6a-4c94-858f-35c799963f97.png)
![image](https://user-images.githubusercontent.com/43498612/229596483-805c99a2-7cff-4d09-94ec-8e169d22de40.png)

**Comment by adriweb** [comment]
Yes, that's on purpose. We (not just me, I've been asked repeatedly over the time) don't want those useless flood messages anymore :P

**Comment by RedGl0w** [comment]
> Yes, that's on purpose. We (not just me, I've been asked repeatedly over the time) don't want anymore of those useless flood :P

Okay my bad, didn't see the messages disappeared too on the global chat, though it was a change in tibot user id or something like that

**Comment by adriweb** [comment]
(note: it was actually a config change specific for this, not a side effect of the other changes)

**Comment by adriweb** [comment]
> Okay my bad, didn't see the messages disappeared too on the global chat, though it was a change in tibot user id or something like that

Note that the messages are still in the DB for audit reasons, they are just not given to clients anymore.

**Comment by RedGl0w** [comment]
So on the bridge there is only the `&online` command to know who's online. It's pretty difficult to use, but I don't immediately see other solution to deliver this information on the bridge...

**Comment by adriweb** [comment]
LGTM
